### ISSUE TITLE
i got these error after install plugin

### ISSUE THREAD

**Issue by saifulazfar** [vuefront/wordpress#2]
i got this error after install the vuefront plugin and cannot activate woocommerce on vuefront setting

`Header information - headers already sent by (output started at /srv/bindings/ce661f7c68bc4050b305cd70005747b2/code/wp-includes/functions.php:4339) in /srv/bindings/ce661f7c68bc4050b305cd70005747b2/code/wp-content/plugins/vuefront/plugin.php on line 173 Warning: Cannot modify header information - headers already sent by (output started at /srv/bindings/ce661f7c68bc4050b305cd70005747b2/code/wp-includes/functions.php:4339) in /srv/bindings/ce661f7c68bc4050b305cd70005747b2/code/wp-content/plugins/vuefront/plugin.php on line 175`

Server info: nginx/1.8.1
PHP version: 7.3.10
Wordpress version: 5.2.3
WooCommerce version: 3.7.1
Vuefront: 1.2.0

**Comment by dmitriyzhuk** [comment]
Hi, please try PHP version 7.2

the library we are using for GraphQL doesn't support php 7.3. but it is the only library that supports older versions which is often the case with old websites. 

we will add support for php7.3. in the future, just a bit later.

**Comment by saifulazfar** [comment]
im using free pantheon.io to test out the vuefront...and it seems that i cannot change the php version...i will try on my localhost to test then...why not using [wp-graphql](https://github.com/wp-graphql/wp-graphql) and [wp-graphql-woocommerce](https://github.com/wp-graphql/wp-graphql-woocommerce) rather than using Graphql-PHP?

**Comment by dmitriyzhuk** [comment]
wp-graphQL uses the same library as we do but a more later version. The idea was that the VueFront Web App is agnostic and has no idea where is the data coming from. 

so it is up to the plugin to implement the schema. we are planning to add a validation based on the php version and pull the right library.
