### ISSUE TITLE
where is the folder dist

### ISSUE THREAD

**Issue by marcelowu** [vuefront/wordpress#3]
Copy all files from folder dist to the newly created vuefront folder,
where is the folder dist?

**Comment by dmitriyzhuk** [comment]
Hi 

have you followed the installation pattern fully? if so, after

```
yarn create vuefront-app
# When promote, provide the CMS Connect URL, which you coppied at step 3.
yarn generate
```
you should have a dist folder on your local computer.

**Comment by marcelowu** [comment]
thanks
