### ISSUE TITLE
how to set up vuefront and Checkout wordpress with the same domain,

### ISSUE THREAD

**Issue by marcelowu** [vuefront/wordpress#4]
how to set up vuefront and Checkout wordpress with the same domain,
![Screenshot from 2020-01-20 21-53-44](https://user-images.githubusercontent.com/30912144/72766627-724adf80-3bcf-11ea-992e-69c154bfc651.png)
![Screenshot from 2020-01-20 21-53-08](https://user-images.githubusercontent.com/30912144/72766628-724adf80-3bcf-11ea-839c-c7bec217fa87.png)

**Comment by dmitriyzhuk** [comment]
Hi, currently we do not have a checkout app that would work as part of VueFront, so it currently redirects to the default WordPress WooCommerce checkout which is... ehg... well are in the stage of developing our first App and it will be you guessed it... Checkout.

**Comment by marcelowu** [comment]
ems domain store https://wordpress.vuefront.com/ 
vuefront                https://wordpress.vuefront.com/
how did you do to be the same?

**Comment by marcelowu** [comment]
ems domain store https://wordpress.vuefront.com/ 
vuefront                https://wordpress.vuefront.com/
how did you do to be the same?

**Comment by marcelowu** [comment]
ems domain store https://wordpress.vuefront.com/ 
vuefront                https://wordpress.vuefront.com/
how did you do to be the same?
