### ISSUE TITLE
error checkout

### ISSUE THREAD

**Issue by marcelowu** [vuefront/wordpress#6]
![Capturar](https://user-images.githubusercontent.com/30912144/74739795-5cfdbb00-5238-11ea-85c1-d00678a46b2b.PNG)

**Comment by dmitriyzhuk** [comment]
that is actually just a page for Wordpress, and we are treating it as a simple page. 
but for woocommerce, it is the page where the checkout is located.

I think the proper way would be for us to ignore it. what do you think?

**Comment by marcelowu** [comment]
![Capturar](https://user-images.githubusercontent.com/30912144/74750725-efa75580-524a-11ea-82b8-03377c40fdb8.PNG)
use another language, how do I solve

**Comment by marcelowu** [comment]
![Capturar](https://user-images.githubusercontent.com/30912144/74781205-d7056280-527f-11ea-84fe-32d371af3b41.PNG)
